// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByMobile(ctx context.Context, mobile pgtype.Text) (User, error)
	GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error)
	GetUsersList(ctx context.Context, arg GetUsersListParams) ([]User, error)
	UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
