// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) 
FROM users 
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, created_at, updated_at, username, password, email, mobile, 
    nickname, avatar_url, role, is_member, member_expire_at, status, 
    banned_until, token, token_expire_at
) VALUES (
    $1, $2, $3, 
    $4, $5, $6, 
    $7, $8, $9, 
    $10, $11, $12, 
    $13, $14, $15, 
    $16
)
RETURNING id, created_at, updated_at, deleted_at, username, password, email, mobile, nickname, avatar_url, role, is_member, member_expire_at, status, banned_until, token, token_expire_at
`

type CreateUserParams struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Username       pgtype.Text        `json:"username"`
	Password       pgtype.Text        `json:"password"`
	Email          pgtype.Text        `json:"email"`
	Mobile         pgtype.Text        `json:"mobile"`
	Nickname       pgtype.Text        `json:"nickname"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	Role           pgtype.Int4        `json:"role"`
	IsMember       pgtype.Bool        `json:"is_member"`
	MemberExpireAt pgtype.Timestamptz `json:"member_expire_at"`
	Status         pgtype.Int4        `json:"status"`
	BannedUntil    pgtype.Timestamptz `json:"banned_until"`
	Token          pgtype.Text        `json:"token"`
	TokenExpireAt  pgtype.Timestamptz `json:"token_expire_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Mobile,
		arg.Nickname,
		arg.AvatarUrl,
		arg.Role,
		arg.IsMember,
		arg.MemberExpireAt,
		arg.Status,
		arg.BannedUntil,
		arg.Token,
		arg.TokenExpireAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Mobile,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Role,
		&i.IsMember,
		&i.MemberExpireAt,
		&i.Status,
		&i.BannedUntil,
		&i.Token,
		&i.TokenExpireAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users 
SET deleted_at = $1, updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type DeleteUserParams struct {
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, created_at, updated_at, deleted_at, username, password, email, mobile, nickname, avatar_url, role, is_member, member_expire_at, status, banned_until, token, token_expire_at
FROM users 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Mobile,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Role,
		&i.IsMember,
		&i.MemberExpireAt,
		&i.Status,
		&i.BannedUntil,
		&i.Token,
		&i.TokenExpireAt,
	)
	return i, err
}

const getUserByMobile = `-- name: GetUserByMobile :one
SELECT id, created_at, updated_at, deleted_at, username, password, email, mobile, nickname, avatar_url, role, is_member, member_expire_at, status, banned_until, token, token_expire_at
FROM users 
WHERE mobile = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByMobile(ctx context.Context, mobile pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByMobile, mobile)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Mobile,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Role,
		&i.IsMember,
		&i.MemberExpireAt,
		&i.Status,
		&i.BannedUntil,
		&i.Token,
		&i.TokenExpireAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, created_at, updated_at, deleted_at, username, password, email, mobile, nickname, avatar_url, role, is_member, member_expire_at, status, banned_until, token, token_expire_at
FROM users 
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Mobile,
		&i.Nickname,
		&i.AvatarUrl,
		&i.Role,
		&i.IsMember,
		&i.MemberExpireAt,
		&i.Status,
		&i.BannedUntil,
		&i.Token,
		&i.TokenExpireAt,
	)
	return i, err
}

const getUsersList = `-- name: GetUsersList :many
SELECT id, created_at, updated_at, deleted_at, username, password, email, mobile, nickname, avatar_url, role, is_member, member_expire_at, status, banned_until, token, token_expire_at
FROM users 
WHERE deleted_at IS NULL 
ORDER BY created_at DESC 
LIMIT $1 OFFSET $2
`

type GetUsersListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUsersList(ctx context.Context, arg GetUsersListParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.Mobile,
			&i.Nickname,
			&i.AvatarUrl,
			&i.Role,
			&i.IsMember,
			&i.MemberExpireAt,
			&i.Status,
			&i.BannedUntil,
			&i.Token,
			&i.TokenExpireAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberStatus = `-- name: UpdateMemberStatus :exec
UPDATE users 
SET is_member = $1, member_expire_at = $2, updated_at = $3
WHERE id = $4 AND deleted_at IS NULL
`

type UpdateMemberStatusParams struct {
	IsMember       pgtype.Bool        `json:"is_member"`
	MemberExpireAt pgtype.Timestamptz `json:"member_expire_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ID             pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error {
	_, err := q.db.Exec(ctx, updateMemberStatus,
		arg.IsMember,
		arg.MemberExpireAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET 
    updated_at = $1, username = $2, password = $3, 
    email = $4, mobile = $5, nickname = $6, 
    avatar_url = $7, role = $8, is_member = $9, 
    member_expire_at = $10, status = $11, 
    banned_until = $12, token = $13, token_expire_at = $14
WHERE id = $15 AND deleted_at IS NULL
`

type UpdateUserParams struct {
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Username       pgtype.Text        `json:"username"`
	Password       pgtype.Text        `json:"password"`
	Email          pgtype.Text        `json:"email"`
	Mobile         pgtype.Text        `json:"mobile"`
	Nickname       pgtype.Text        `json:"nickname"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	Role           pgtype.Int4        `json:"role"`
	IsMember       pgtype.Bool        `json:"is_member"`
	MemberExpireAt pgtype.Timestamptz `json:"member_expire_at"`
	Status         pgtype.Int4        `json:"status"`
	BannedUntil    pgtype.Timestamptz `json:"banned_until"`
	Token          pgtype.Text        `json:"token"`
	TokenExpireAt  pgtype.Timestamptz `json:"token_expire_at"`
	ID             pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.UpdatedAt,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Mobile,
		arg.Nickname,
		arg.AvatarUrl,
		arg.Role,
		arg.IsMember,
		arg.MemberExpireAt,
		arg.Status,
		arg.BannedUntil,
		arg.Token,
		arg.TokenExpireAt,
		arg.ID,
	)
	return err
}
