// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupons.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserCoupons = `-- name: CountUserCoupons :one
SELECT COUNT(*) 
FROM user_coupons 
WHERE user_id = $1 AND coupon_id = $2 AND deleted_at IS NULL
`

type CountUserCouponsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CouponID pgtype.UUID `json:"coupon_id"`
}

func (q *Queries) CountUserCoupons(ctx context.Context, arg CountUserCouponsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserCoupons, arg.UserID, arg.CouponID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
    id, created_at, updated_at, name, total, stock, amount, start_time, end_time
) VALUES (
    $1, $2, $3, 
    $4, $5, $6, 
    $7, $8, $9
)
RETURNING id, created_at, updated_at, deleted_at, name, total, stock, amount, start_time, end_time
`

type CreateCouponParams struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Name      pgtype.Text        `json:"name"`
	Total     pgtype.Int4        `json:"total"`
	Stock     pgtype.Int4        `json:"stock"`
	Amount    pgtype.Numeric     `json:"amount"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Total,
		arg.Stock,
		arg.Amount,
		arg.StartTime,
		arg.EndTime,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Total,
		&i.Stock,
		&i.Amount,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const createUserCoupon = `-- name: CreateUserCoupon :one
INSERT INTO user_coupons (
    id, created_at, updated_at, user_id, coupon_id, status
) VALUES (
    $1, $2, $3, 
    $4, $5, $6
)
RETURNING id, created_at, updated_at, deleted_at, user_id, coupon_id, status
`

type CreateUserCouponParams struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	CouponID  pgtype.UUID        `json:"coupon_id"`
	Status    pgtype.Int4        `json:"status"`
}

func (q *Queries) CreateUserCoupon(ctx context.Context, arg CreateUserCouponParams) (UserCoupon, error) {
	row := q.db.QueryRow(ctx, createUserCoupon,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.CouponID,
		arg.Status,
	)
	var i UserCoupon
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.CouponID,
		&i.Status,
	)
	return i, err
}

const decreaseCouponStock = `-- name: DecreaseCouponStock :exec
UPDATE coupons 
SET stock = stock - 1, updated_at = $1
WHERE id = $2 AND deleted_at IS NULL AND stock > 0
`

type DecreaseCouponStockParams struct {
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) DecreaseCouponStock(ctx context.Context, arg DecreaseCouponStockParams) error {
	_, err := q.db.Exec(ctx, decreaseCouponStock, arg.UpdatedAt, arg.ID)
	return err
}

const getCouponByID = `-- name: GetCouponByID :one
SELECT id, created_at, updated_at, deleted_at, name, total, stock, amount, start_time, end_time
FROM coupons 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCouponByID(ctx context.Context, id pgtype.UUID) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByID, id)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Total,
		&i.Stock,
		&i.Amount,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const getUserCoupon = `-- name: GetUserCoupon :one
SELECT id, created_at, updated_at, deleted_at, user_id, coupon_id, status
FROM user_coupons 
WHERE user_id = $1 AND coupon_id = $2 AND deleted_at IS NULL
`

type GetUserCouponParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CouponID pgtype.UUID `json:"coupon_id"`
}

func (q *Queries) GetUserCoupon(ctx context.Context, arg GetUserCouponParams) (UserCoupon, error) {
	row := q.db.QueryRow(ctx, getUserCoupon, arg.UserID, arg.CouponID)
	var i UserCoupon
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.CouponID,
		&i.Status,
	)
	return i, err
}
