// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUserCoupons(ctx context.Context, arg CountUserCouponsParams) (int64, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	CreateUserCoupon(ctx context.Context, arg CreateUserCouponParams) (UserCoupon, error)
	DecreaseCouponStock(ctx context.Context, arg DecreaseCouponStockParams) error
	GetCouponByID(ctx context.Context, id pgtype.UUID) (Coupon, error)
	GetUserCoupon(ctx context.Context, arg GetUserCouponParams) (UserCoupon, error)
}

var _ Querier = (*Queries)(nil)
