DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS post_topics;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS topics;

ALTER TABLE users DROP COLUMN IF EXISTS is_member;
ALTER TABLE users DROP COLUMN IF EXISTS member_expire_at;
