// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByPostID = `-- name: CountCommentsByPostID :one
SELECT COUNT(*) 
FROM comments 
WHERE deleted_at IS NULL AND post_id = $1
`

func (q *Queries) CountCommentsByPostID(ctx context.Context, postID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByPostID, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) 
FROM posts 
WHERE deleted_at IS NULL AND status = $1
`

func (q *Queries) CountPosts(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    id, created_at, updated_at, user_id, post_id, content
) VALUES (
    $1, $2, $3, 
    $4, $5, $6
)
RETURNING id, created_at, updated_at, deleted_at, user_id, post_id, content
`

type CreateCommentParams struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	Content   pgtype.Text        `json:"content"`
}

type CreateCommentRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	Content   pgtype.Text        `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.PostID,
		arg.Content,
	)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.PostID,
		&i.Content,
	)
	return i, err
}

const createLike = `-- name: CreateLike :one
INSERT INTO likes (
    id, created_at, updated_at, user_id, target_id, target_type
) VALUES (
    $1, $2, $3, 
    $4, $5, $6
)
RETURNING id, created_at, updated_at, deleted_at, user_id, target_id, target_type
`

type CreateLikeParams struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     pgtype.UUID        `json:"user_id"`
	TargetID   pgtype.UUID        `json:"target_id"`
	TargetType pgtype.Text        `json:"target_type"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.db.QueryRow(ctx, createLike,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.TargetID,
		arg.TargetType,
	)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.TargetID,
		&i.TargetType,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id, created_at, updated_at, user_id, content, status
) VALUES (
    $1, $2, $3, 
    $4, $5, $6
)
RETURNING id, created_at, updated_at, deleted_at, user_id, content, status
`

type CreatePostParams struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   pgtype.Text        `json:"content"`
	Status    pgtype.Text        `json:"status"`
}

type CreatePostRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   pgtype.Text        `json:"content"`
	Status    pgtype.Text        `json:"status"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.Content,
		arg.Status,
	)
	var i CreatePostRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Content,
		&i.Status,
	)
	return i, err
}

const deleteLike = `-- name: DeleteLike :exec
UPDATE likes 
SET deleted_at = $1, updated_at = $2
WHERE user_id = $3 AND target_id = $4 AND target_type = $5 AND deleted_at IS NULL
`

type DeleteLikeParams struct {
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     pgtype.UUID        `json:"user_id"`
	TargetID   pgtype.UUID        `json:"target_id"`
	TargetType pgtype.Text        `json:"target_type"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.TargetID,
		arg.TargetType,
	)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, created_at, updated_at, deleted_at, user_id, post_id, content
FROM comments 
WHERE id = $1 AND deleted_at IS NULL
`

type GetCommentByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	Content   pgtype.Text        `json:"content"`
}

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.PostID,
		&i.Content,
	)
	return i, err
}

const getCommentsByPostID = `-- name: GetCommentsByPostID :many
SELECT id, created_at, updated_at, deleted_at, user_id, post_id, content
FROM comments 
WHERE deleted_at IS NULL AND post_id = $1
ORDER BY created_at ASC 
LIMIT $2 OFFSET $3
`

type GetCommentsByPostIDParams struct {
	PostID pgtype.UUID `json:"post_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetCommentsByPostIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	Content   pgtype.Text        `json:"content"`
}

func (q *Queries) GetCommentsByPostID(ctx context.Context, arg GetCommentsByPostIDParams) ([]GetCommentsByPostIDRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByPostID, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentsByPostIDRow{}
	for rows.Next() {
		var i GetCommentsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.PostID,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, created_at, updated_at, deleted_at, user_id, content, status
FROM posts 
WHERE id = $1 AND deleted_at IS NULL
`

type GetPostByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   pgtype.Text        `json:"content"`
	Status    pgtype.Text        `json:"status"`
}

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (GetPostByIDRow, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i GetPostByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Content,
		&i.Status,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT id, created_at, updated_at, deleted_at, user_id, content, status
FROM posts 
WHERE deleted_at IS NULL AND status = $1
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type GetPostsParams struct {
	Status pgtype.Text `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetPostsRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   pgtype.Text        `json:"content"`
	Status    pgtype.Text        `json:"status"`
}

func (q *Queries) GetPosts(ctx context.Context, arg GetPostsParams) ([]GetPostsRow, error) {
	rows, err := q.db.Query(ctx, getPosts, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostsRow{}
	for rows.Next() {
		var i GetPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.Content,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostStatus = `-- name: UpdatePostStatus :exec
UPDATE posts 
SET status = $1, updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type UpdatePostStatusParams struct {
	Status    pgtype.Text        `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) error {
	_, err := q.db.Exec(ctx, updatePostStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
