// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCommentsByPostID = `-- name: CountCommentsByPostID :one
SELECT COUNT(*) 
FROM comments 
WHERE deleted_at IS NULL AND post_id = $1
`

func (q *Queries) CountCommentsByPostID(ctx context.Context, postID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCommentsByPostID, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) 
FROM posts 
WHERE deleted_at IS NULL AND status = $1
`

func (q *Queries) CountPosts(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countPosts, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    id, created_at, updated_at, user_id, post_id, content, parent_id, root_id, level
) VALUES (
    $1, $2, $3, 
    $4, $5, $6, 
    $7, $8, $9
)
RETURNING id, created_at, updated_at, deleted_at, user_id, post_id, content, parent_id, root_id, level
`

type CreateCommentParams struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	Content   pgtype.Text        `json:"content"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	RootID    pgtype.UUID        `json:"root_id"`
	Level     pgtype.Int4        `json:"level"`
}

type CreateCommentRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	Content   pgtype.Text        `json:"content"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	RootID    pgtype.UUID        `json:"root_id"`
	Level     pgtype.Int4        `json:"level"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.PostID,
		arg.Content,
		arg.ParentID,
		arg.RootID,
		arg.Level,
	)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.PostID,
		&i.Content,
		&i.ParentID,
		&i.RootID,
		&i.Level,
	)
	return i, err
}

const createLike = `-- name: CreateLike :one
INSERT INTO likes (
    id, created_at, updated_at, user_id, target_id, target_type
) VALUES (
    $1, $2, $3, 
    $4, $5, $6
)
RETURNING id, created_at, updated_at, deleted_at, user_id, target_id, target_type
`

type CreateLikeParams struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     pgtype.UUID        `json:"user_id"`
	TargetID   pgtype.UUID        `json:"target_id"`
	TargetType pgtype.Text        `json:"target_type"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.db.QueryRow(ctx, createLike,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.TargetID,
		arg.TargetType,
	)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.TargetID,
		&i.TargetType,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
    id, created_at, updated_at, user_id, content, media_urls, type, status
) VALUES (
    $1, $2, $3, 
    $4, $5, $6, 
    $7, $8
)
RETURNING id, created_at, updated_at, deleted_at, user_id, content, media_urls, type, status
`

type CreatePostParams struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   pgtype.Text        `json:"content"`
	MediaUrls []byte             `json:"media_urls"`
	Type      pgtype.Text        `json:"type"`
	Status    pgtype.Text        `json:"status"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.Content,
		arg.MediaUrls,
		arg.Type,
		arg.Status,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Content,
		&i.MediaUrls,
		&i.Type,
		&i.Status,
	)
	return i, err
}

const createPostTopic = `-- name: CreatePostTopic :exec
INSERT INTO post_topics (post_id, topic_id) VALUES ($1, $2)
`

type CreatePostTopicParams struct {
	PostID  pgtype.UUID `json:"post_id"`
	TopicID pgtype.UUID `json:"topic_id"`
}

func (q *Queries) CreatePostTopic(ctx context.Context, arg CreatePostTopicParams) error {
	_, err := q.db.Exec(ctx, createPostTopic, arg.PostID, arg.TopicID)
	return err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (
    id, created_at, updated_at, name
) VALUES (
    $1, $2, $3, 
    $4
)
RETURNING id, created_at, updated_at, deleted_at, name
`

type CreateTopicParams struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Name      pgtype.Text        `json:"name"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
	)
	return i, err
}

const deleteLike = `-- name: DeleteLike :exec
UPDATE likes 
SET deleted_at = $1, updated_at = $2
WHERE user_id = $3 AND target_id = $4 AND target_type = $5 AND deleted_at IS NULL
`

type DeleteLikeParams struct {
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     pgtype.UUID        `json:"user_id"`
	TargetID   pgtype.UUID        `json:"target_id"`
	TargetType pgtype.Text        `json:"target_type"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.TargetID,
		arg.TargetType,
	)
	return err
}

const deletePostTopic = `-- name: DeletePostTopic :exec
DELETE FROM post_topics WHERE post_id = $1 AND topic_id = $2
`

type DeletePostTopicParams struct {
	PostID  pgtype.UUID `json:"post_id"`
	TopicID pgtype.UUID `json:"topic_id"`
}

func (q *Queries) DeletePostTopic(ctx context.Context, arg DeletePostTopicParams) error {
	_, err := q.db.Exec(ctx, deletePostTopic, arg.PostID, arg.TopicID)
	return err
}

const getAllTopics = `-- name: GetAllTopics :many
SELECT id, created_at, updated_at, deleted_at, name
FROM topics 
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetAllTopics(ctx context.Context) ([]Topic, error) {
	rows, err := q.db.Query(ctx, getAllTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Topic{}
	for rows.Next() {
		var i Topic
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, created_at, updated_at, deleted_at, user_id, post_id, content, parent_id, root_id, level
FROM comments 
WHERE id = $1 AND deleted_at IS NULL
`

type GetCommentByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	Content   pgtype.Text        `json:"content"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	RootID    pgtype.UUID        `json:"root_id"`
	Level     pgtype.Int4        `json:"level"`
}

func (q *Queries) GetCommentByID(ctx context.Context, id pgtype.UUID) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.PostID,
		&i.Content,
		&i.ParentID,
		&i.RootID,
		&i.Level,
	)
	return i, err
}

const getCommentsByPostID = `-- name: GetCommentsByPostID :many
SELECT id, created_at, updated_at, deleted_at, user_id, post_id, content, parent_id, root_id, level
FROM comments 
WHERE deleted_at IS NULL AND post_id = $1
ORDER BY created_at ASC 
LIMIT $2 OFFSET $3
`

type GetCommentsByPostIDParams struct {
	PostID pgtype.UUID `json:"post_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetCommentsByPostIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	PostID    pgtype.UUID        `json:"post_id"`
	Content   pgtype.Text        `json:"content"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	RootID    pgtype.UUID        `json:"root_id"`
	Level     pgtype.Int4        `json:"level"`
}

func (q *Queries) GetCommentsByPostID(ctx context.Context, arg GetCommentsByPostIDParams) ([]GetCommentsByPostIDRow, error) {
	rows, err := q.db.Query(ctx, getCommentsByPostID, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCommentsByPostIDRow{}
	for rows.Next() {
		var i GetCommentsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.PostID,
			&i.Content,
			&i.ParentID,
			&i.RootID,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikeByUserAndTarget = `-- name: GetLikeByUserAndTarget :one
SELECT id, created_at, updated_at, deleted_at, user_id, target_id, target_type
FROM likes 
WHERE user_id = $1 AND target_id = $2 AND target_type = $3 AND deleted_at IS NULL
`

type GetLikeByUserAndTargetParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	TargetID   pgtype.UUID `json:"target_id"`
	TargetType pgtype.Text `json:"target_type"`
}

func (q *Queries) GetLikeByUserAndTarget(ctx context.Context, arg GetLikeByUserAndTargetParams) (Like, error) {
	row := q.db.QueryRow(ctx, getLikeByUserAndTarget, arg.UserID, arg.TargetID, arg.TargetType)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.TargetID,
		&i.TargetType,
	)
	return i, err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, created_at, updated_at, deleted_at, user_id, content, media_urls, type, status
FROM posts 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Content,
		&i.MediaUrls,
		&i.Type,
		&i.Status,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT id, created_at, updated_at, deleted_at, user_id, content, media_urls, type, status
FROM posts 
WHERE deleted_at IS NULL AND status = $1
ORDER BY created_at DESC 
LIMIT $2 OFFSET $3
`

type GetPostsParams struct {
	Status pgtype.Text `json:"status"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetPosts(ctx context.Context, arg GetPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, getPosts, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.Content,
			&i.MediaUrls,
			&i.Type,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicByName = `-- name: GetTopicByName :one
SELECT id, created_at, updated_at, deleted_at, name
FROM topics 
WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTopicByName(ctx context.Context, name string) (Topic, error) {
	row := q.db.QueryRow(ctx, getTopicByName, name)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
	)
	return i, err
}

const updatePostStatus = `-- name: UpdatePostStatus :exec
UPDATE posts 
SET status = $1, updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type UpdatePostStatusParams struct {
	Status    pgtype.Text        `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	ID        pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) error {
	_, err := q.db.Exec(ctx, updatePostStatus, arg.Status, arg.UpdatedAt, arg.ID)
	return err
}
