// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCommentsByPostID(ctx context.Context, postID pgtype.UUID) (int64, error)
	CountPosts(ctx context.Context, status pgtype.Text) (int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error)
	CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error)
	DeleteLike(ctx context.Context, arg DeleteLikeParams) error
	GetCommentByID(ctx context.Context, id pgtype.UUID) (GetCommentByIDRow, error)
	GetCommentsByPostID(ctx context.Context, arg GetCommentsByPostIDParams) ([]GetCommentsByPostIDRow, error)
	GetPostByID(ctx context.Context, id pgtype.UUID) (GetPostByIDRow, error)
	GetPosts(ctx context.Context, arg GetPostsParams) ([]GetPostsRow, error)
	UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) error
}

var _ Querier = (*Queries)(nil)
