// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	PostID    pgtype.UUID        `json:"post_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   pgtype.Text        `json:"content"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	RootID    pgtype.UUID        `json:"root_id"`
	Level     pgtype.Int4        `json:"level"`
}

type Coupon struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Name      string             `json:"name"`
	Total     int32              `json:"total"`
	Stock     int32              `json:"stock"`
	Amount    pgtype.Numeric     `json:"amount"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

type Like struct {
	ID         pgtype.UUID        `json:"id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	UserID     pgtype.UUID        `json:"user_id"`
	TargetID   pgtype.UUID        `json:"target_id"`
	TargetType pgtype.Text        `json:"target_type"`
}

type Order struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	OrderNo     string             `json:"order_no"`
	UserID      pgtype.UUID        `json:"user_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Status      pgtype.Text        `json:"status"`
	Channel     pgtype.Text        `json:"channel"`
	Subject     pgtype.Text        `json:"subject"`
	ExtraParams []byte             `json:"extra_params"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
}

type Post struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	Content   pgtype.Text        `json:"content"`
	MediaUrls []byte             `json:"media_urls"`
	Type      pgtype.Text        `json:"type"`
	Status    pgtype.Text        `json:"status"`
}

type PostTopic struct {
	PostID  pgtype.UUID `json:"post_id"`
	TopicID pgtype.UUID `json:"topic_id"`
}

type Topic struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Name      string             `json:"name"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
	Username       pgtype.Text        `json:"username"`
	Password       pgtype.Text        `json:"password"`
	Email          pgtype.Text        `json:"email"`
	Mobile         pgtype.Text        `json:"mobile"`
	Nickname       pgtype.Text        `json:"nickname"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	Role           pgtype.Int4        `json:"role"`
	IsMember       pgtype.Bool        `json:"is_member"`
	MemberExpireAt pgtype.Timestamptz `json:"member_expire_at"`
	Status         pgtype.Int4        `json:"status"`
	BannedUntil    pgtype.Timestamptz `json:"banned_until"`
	Token          pgtype.Text        `json:"token"`
	TokenExpireAt  pgtype.Timestamptz `json:"token_expire_at"`
}

type UserCoupon struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	CouponID  pgtype.UUID        `json:"coupon_id"`
	Status    pgtype.Int4        `json:"status"`
}
