// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id, created_at, updated_at, order_no, user_id, amount, status, channel, subject, extra_params, paid_at
) VALUES (
    $1, $2, $3, 
    $4, $5, $6, 
    $7, $8, $9, 
    $10, $11
)
RETURNING id, created_at, updated_at, deleted_at, order_no, user_id, amount, status, channel, subject, extra_params, paid_at
`

type CreateOrderParams struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OrderNo     pgtype.Text        `json:"order_no"`
	UserID      pgtype.UUID        `json:"user_id"`
	Amount      pgtype.Numeric     `json:"amount"`
	Status      pgtype.Text        `json:"status"`
	Channel     pgtype.Text        `json:"channel"`
	Subject     pgtype.Text        `json:"subject"`
	ExtraParams []byte             `json:"extra_params"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.OrderNo,
		arg.UserID,
		arg.Amount,
		arg.Status,
		arg.Channel,
		arg.Subject,
		arg.ExtraParams,
		arg.PaidAt,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrderNo,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.Channel,
		&i.Subject,
		&i.ExtraParams,
		&i.PaidAt,
	)
	return i, err
}

const getOrderByNo = `-- name: GetOrderByNo :one
SELECT id, created_at, updated_at, deleted_at, order_no, user_id, amount, status, channel, subject, extra_params, paid_at
FROM orders 
WHERE order_no = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrderByNo(ctx context.Context, orderNo string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByNo, orderNo)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OrderNo,
		&i.UserID,
		&i.Amount,
		&i.Status,
		&i.Channel,
		&i.Subject,
		&i.ExtraParams,
		&i.PaidAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders 
SET status = $1, paid_at = $2, updated_at = $3, extra_params = $4
WHERE order_no = $5 AND deleted_at IS NULL
`

type UpdateOrderStatusParams struct {
	Status      pgtype.Text        `json:"status"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ExtraParams []byte             `json:"extra_params"`
	OrderNo     string             `json:"order_no"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus,
		arg.Status,
		arg.PaidAt,
		arg.UpdatedAt,
		arg.ExtraParams,
		arg.OrderNo,
	)
	return err
}
